### ISSUE TITLE
asteroid and btime ini files

### ISSUE THREAD

**Issue by toccata10** [finalburnneo/FBNeo-cheats#1]
Hi,
Thanks for this very useful repo.
After trying to convert those ini files to cht files, I discovered that they were usable directly in retroarch with that:
https://github.com/libretro/FBNeo/tree/master/src/burner/libretro#how-do-i-use-cheat-code-
So much easier !

I couldn't find the asteroid, nor btime cheat files, so I created them by using some of the cheats from mame xml files (I didn't try to incorporate everything, just what is of interest to me).
I know, I should do a PR, but it's probably way simpler for me to send them in this issue report.
[asteroid.ini.zip](https://github.com/finalburnneo/FBNeo-cheats/files/5421371/asteroid.ini.zip)
[btime.ini.zip](https://github.com/finalburnneo/FBNeo-cheats/files/5421386/btime.ini.zip)

**Comment by barbudreadmon** [comment]
thanks, i'll include them in the repo later today :)

**Comment by barbudreadmon** [comment]
I totally forgot about those ! Thanks again for your contribution, they are now part of the repo :)
