### ISSUE TITLE
more cheats

### ISSUE THREAD

**Issue by jmodlin210** [finalburnneo/FBNeo-cheats#5]
There are no cheats for the arcade games for final burn neo emulator for captain America and the avengers with clones, mystic warriors with clones, bucky o'hare with clones, wild west of cowboys moo mesa with clones, wonder boy in monster land with clones, spider-man with clones, splatterhouse with clones, batman, battletoads, mk, mk2, mk3, umk3, all cps1 games, cps2 games, cps3 games, neo geo games, etc. with a lot more cheats. thank you.

**Comment by barbudreadmon** [comment]
FBNeo requires external cheat file(s), you just need a cheat file with those games...
At this point, i don't know what's wrong with you, but to us it only seems like you are trolling, and this is getting on the nerves of everyone in the team, so we'll be thankful if you stop reporting things to us.
I hope i'll never have to see one of your "reports" again, bye.
