### ISSUE TITLE
Requesting NBAJamTE 2.1 arcade cheats for FBNeo

### ISSUE THREAD

**Issue by xdegenerate** [finalburnneo/FBNeo-cheats#6]
Hi. There's an awesome NBAJAM mod called NBAJAMRewind I would like to get some cheats for. Mostly I just want unlimited on fire. It's running on Nbajamte rev 2.1.

**Comment by barbudreadmon** [comment]
see answer on forum

**Comment by xdegenerate** [comment]
Sorry, where is the forum? 
--
Sent from myMail for Android Saturday, 06 August 2022, 04:28pm +10:00 from barbudreadmon  ***@***.*** :

**Comment by barbudreadmon** [comment]
https://neo-source.com/index.php?topic=139.msg34373#msg34373

**Comment by xdegenerate** [comment]
Oh, that place. Thank you. 
--
Sent from myMail for Android Saturday, 06 August 2022, 04:47pm +10:00 from barbudreadmon  ***@***.*** :
